= Joel Glover 

== About me

A creative problem solver, technical communicator and
computer aided designer with a background in automotive
mechanics, robotics, motion control, additive manufacturing,
medical simulation, microscopy, lasers and physics.

== Programming
* C#
* Java
* Python

== Software

* Autodesk Fusion 360
* MadCap Flare
* Rhino
* Inkscape

== Skills



== Work experience


**Application Scientist** | Polaris Motion

October 2021 -> September 2022

* Team lead of technical support and application
engineering.
* Leveraged my communication and troubleshooting skills to provide an excellent customer experience.
* Direct customer communications and technical documentation/knowledge base improvements.
* Maintained Laser CNC equipment, CAD work for machine upgrades and suggesting software/electrical-hardware improvements to products based on experimentation and customer feedback.

**Instrumentation Specialist** | Live Cell Imaging Laboratory

May 2016 -> July 2021

* Responsible for maintaining, troubleshooting and
repairing all instruments/computers within the
8,000 square foot facility and managing the 3D
printing lab. 
* I provided design services to
researchers for custom experimental devices and
taught Masters courses on design, 3D-printing
and creating prototypes for startups.

== Education
**Bachelor of Science in Physics** | University of Calgary

September 2014 -> February 2020

== Publications

Duong, K., Glover, J., Perry, A. C., Olmstead, D., Ungrin, M.,
Colarusso, P., ... & Martin, A. R. (2021). Feasibility of three-
dimensional facial imaging and printing for producing
customised nasal masks for continuous positive airway
pressure. ERJ Open Research, 7(1).

== Awards

> *GRC Initiative Award*
> 
> Recognition of students who have improved the UCalgary graduate student experience

> *Dean's List*
> 
> Named to the 2016 Faculty of Science Dean's List